Deprecations and improvements
InternationalScratchWiki/scratch-confirmaccount-v3 pull request #170
Opened 2022-10-10 10:16 UTC by apple502j

Resolves #151
Resolves #160
Resolves #168
Resolves #169

## Breaking changes
- Requires MW1.35+.
- Several hooks have been renamed to avoid conflict. This affects other extensions with CA3 integration.

## Bugfixes
- Fixed a bug where block expiry option "existing" and "othertime" were incorrectly displayed in non-English locale.
- Fixed PHP warning being displayed while checking if a user is a New Scratcher.
- Fixed deprecation warning on PHP8.2 due to passing `null` to `strpos` in `SpecialConfirmAccounts`.
- Fixed a bug where password confirmation match used weak comparison. This does not affect actual login.
- Fixed a bug where session invalid error showed raw HTML.

## New features
- For account blocks with expiration, show the duration; this continues to be not displayed for infinite blocks.
- Alt account request warning now includes the link to the latest request, its request date and status.
- Alt account edit/Checkuser warning now includes the link to the user/talk/contrib and the last edit date.
- Alt account and checkuser warnings are now shown in descending order.

## Internationalization related changes
- New strings added: `scratch-confirmaccount-verification-project`, `scratch-confirmaccount-ip-warning-request-time`, `scratch-confirmaccount-ip-warning-checkuser-time`, `scratch-confirmaccount-user-blocked-duration`.
- `scratch-confirmaccount-vercode-explanation` no longer links to the project directly; the link is now constructed by code, to allow `target=_blank`. All locales have been updated.
- Removed unused string `scratch-confirmaccount-waiting-request`.
- Updated Japanese translation.
- Added new and missing `qqq` translation.

## Technical and internal changes
- Manifest schema version is now 2. This includes config object change. The file is also formatted.
- Added editorconfig and gitignore.
- Added typehint to some methods.
- Replaced `==` with `===`, etc.
- Removed unused variables.
- Replaced `wfGetDB` with `ILoadBalancer::getConnection`.
- Conditionally replaced `DB_MASTER` with `DB_PRIMARY`.
- Hook system completely rewritten to use `HookHandler`.
- Dependency injection is now used in several places.
- `accountRequestFormData` now returns HTML.
- Fixed session request ID sometimes being integer and sometimes string; this is now always string.
- Fixed a bug where `AccountRequestSubmitted` hook could fire multiple times.
- Fixed a bug with PHPDoc showing a wrong type.

2022-10-10 16:07 UTC, jacob-g reviewed
Overall looks pretty good other than a few minor mostly cosmetic things I pointed out. I'll run this on my local (MW 1.39 and PHP 8.1) when I get the chance to make sure this all works.

Thank you for all the work you put into this, it really means a lot and makes my life so much easier.

2022-10-10 16:07 UTC, jacob-g commented on src/SpecialRequestAccount.php
> +		$passwordFactory = $this->passwordFactory;
Notpicking a bit here but I think this line is unnecessary, you can just use `$this->passwordFactory` further on down

2022-10-10 16:07 UTC, jacob-g commented on src/SpecialRequestAccount.php
> +		} else if ($par === null || $par === '') {
Could we use `empty($par)` instead? Seems a bit cleaner

2022-10-10 16:07 UTC, jacob-g commented on src/database/DatabaseInteractions.php
> +		if (in_array($row->request_username, $usernames)) continue;
Fix indentation

2022-10-10 16:19 UTC, jacob-g reviewed
MediaWiki still tells me that the PersonalUrls hook is deprecated. I guess add a ticket to remove it once we do the real upgrade?

2022-10-10 16:24 UTC, jacob-g reviewed
![image](https://user-images.githubusercontent.com/1960707/194912150-0bbdcb99-d904-4156-97ee-db7c00db711f.png)
Looks like the error display is no longer in the red box, we may need to migrate that styling.

Edit: never mind, this is an issue with SWS, will file a ticket there.

2022-10-10 16:26 UTC, jacob-g reviewed
Login intercept also isn't showing that nicely:
![image](https://user-images.githubusercontent.com/1960707/194912521-7eefc206-4ccf-4830-8e03-de79ab837e1c.png)

2022-10-10 16:31 UTC, jacob-g reviewed
Got this deprecation when queueing a job:
```
 Deprecated: Use of JobQueueGroup::singleton was deprecated in MediaWiki 1.37. [Called from handleRequestActionSubmission in /var/www/html/w/extensions/scratch-confirmaccount-v3/src/subpages/RequestPage.php at line 647] in /var/www/html/w/includes/debug/MWDebug.php on line 381
```

2022-10-10 16:32 UTC, jacob-g requested changes
Special:ConfirmAccounts fails for me with this when I try to view a request:
```
Error: Call to undefined method User::getCanonicalName()

Backtrace:

from /var/www/html/w/extensions/scratch-confirmaccount-v3/src/subpages/RequestPage.php(438)
#0 /var/www/html/w/extensions/scratch-confirmaccount-v3/src/subpages/RequestPage.php(516): requestCheckUserDisplay()
#1 /var/www/html/w/extensions/scratch-confirmaccount-v3/src/SpecialConfirmAccounts.php(451): requestPage()
#2 /var/www/html/w/includes/specialpage/SpecialPage.php(701): SpecialConfirmAccounts->execute()
#3 /var/www/html/w/includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run()
#4 /var/www/html/w/includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#5 /var/www/html/w/includes/MediaWiki.php(904): MediaWiki->performRequest()
#6 /var/www/html/w/includes/MediaWiki.php(562): MediaWiki->main()
#7 /var/www/html/w/index.php(50): MediaWiki->run()
#8 /var/www/html/w/index.php(46): wfIndexMain()
#9 {main}
```

This is the end of my review for now. I will continue reviewing when this is fixed.

2022-10-10 20:44 UTC, Kenny2github requested changes

2022-10-11 02:55 UTC, apple502j commented
`JobQueueGroup` will remain untouched (will fix after dropping 1.35) - no clean way to make it work for both. The replacement is added in 1.37.

2022-10-11 02:58 UTC, jacob-g commented
@apple502j I put a new ticket (#171) in for removing `JobQueueGroup::singleton` for when we upgrade to 1.39 so we can still keep track of it.

2022-10-11 15:35 UTC, jacob-g commented
Did a smoke test of the request flow, seems to work without any issues other than the remaining deprecations that will need to wait until we actually do the 1.39 upgrade.

2022-10-11 15:39 UTC, jacob-g requested changes
Make the changes to the .gitignore and we should be good to go here. Thank you for all the work you put into this.

2022-10-11 15:39 UTC, jacob-g commented on .gitignore
> +.DS_Store
```suggestion

```

2022-10-11 15:39 UTC, jacob-g commented on .gitignore
> +Thumbs.db
```suggestion

```

2022-10-12 01:52 UTC, jacob-g reviewed
At this point I think we're ready to go. Tomorrow I'll test this on staging (still on MW 1.35) to make absolutely sure it works with all our other stuff and won't break production when we deploy it. Stay tuned.

2022-10-12 15:06 UTC, jacob-g approved these changes
Tested on staging, looks good. Ready to merge.

2022-10-13 02:20 UTC, Kenny2github approved these changes
Did a rejection test on staging, LGTM

2022-10-13 02:20 UTC, merged