Specify language in scraper so it doesn't look for the wrong thing
InternationalScratchWiki/scratch-confirmaccount-v3 pull request #195
Opened 2023-12-06 20:36 UTC by mrsrec

This is a copy of #192 which was mistakenly closed by deleting the fork that the code was in.

Original text:

"Depending on a web server's configuration or location, it may get back a response with a language besides English, breaking the scraper. This fixes that.

This does not currently affect en.scratch-wiki.info because it doesn't put an Accept-Language header by default, and Scratch ignores IP addresses, but it will affect other web servers and may affect en.scratch-wiki.info as well should either of the two aforementioned things change."

Closes #191

2023-12-06 20:38 UTC, mrsrec commented
Closes #191

2024-03-12 20:16 UTC, jacob-g requested changes

2024-03-12 20:16 UTC, jacob-g commented on src/verification/ScratchUserCheck.php
> +		$html = @file_get_contents($url, false, stream_context_create(
![image](https://github.com/InternationalScratchWiki/scratch-confirmaccount-v3/assets/1960707/eba1224f-bd49-43c6-ad6c-1384438478c3)
Make sure to wrap the outer part of the array properly. I believe it should be:
```php
stream_context_create([
  "http" => ["header" => "Accept-Language: en\r\nCookie: scratchlanguage=en"]
])```

Also a more minor detail: single quotes are preferred over double quotes unless you are specifically intending to use variable interpolation or escape sequences.

2024-03-12 20:41 UTC, mrsrec commented
@jacob-g Might be web server-specific. Added your changes

2024-03-12 20:45 UTC, jacob-g requested changes

2024-03-12 20:45 UTC, jacob-g commented on src/verification/ScratchUserCheck.php
> +			'http' => ['header' => 'Accept-Language: en\r\nCookie: scratchlanguage=en']
I suppose I should have been clearer with the single quotes: it's right for http and header, but for the body you actually do want double quotes due to the use of \r and \n.

2024-03-12 20:45 UTC, jacob-g commented
Other than the quote thing, looks good now. Fix that and we're good to go.

2024-03-13 04:54 UTC, mrsrec commented
OK, now?

2024-08-07 22:12 UTC, closed without merging