Copy button
InternationalScratchWiki/scratch-confirmaccount-v3 pull request #74
Opened 2020-10-07 07:12 UTC by ahmetlii

I did a button for copying to clipboard. Closes #73

2020-10-07 16:46 UTC, apple502j requested changes

2020-10-07 16:46 UTC, apple502j commented on src/SpecialRequestAccount.php
> +				'onclick' => 'copyToClipboard(document.getElementById("mw-scratch-confirmaccount-verifcode").textContent)',
Don't use onclick. Add to the JS file.

2020-10-07 16:46 UTC, apple502j commented on src/SpecialRequestAccount.php
> +				'value' => 'document.getElementById("mw-scratch-confirmaccount-verifcode").textContent'
This is not how things work.

2020-10-07 16:46 UTC, apple502j commented on src/SpecialRequestAccount.php
> +			'Copy to clipboard'
i18n

2020-10-07 16:46 UTC, apple502j commented on resources/main.js
> +        var tempItem = document.createElement('textarea');
I think reusing existing textarea is enough.

2020-10-07 16:46 UTC, ahmetlii commented on src/SpecialRequestAccount.php
> +				'onclick' => 'copyToClipboard(document.getElementById("mw-scratch-confirmaccount-verifcode").textContent)',
ok

2020-10-08 11:05 UTC, ahmetlii commented
@apple502j can you re-review it and merge again?

2020-10-09 19:10 UTC, ahmetlii commented
@jacob-g can you just review and accept if possible?

2020-10-10 19:43 UTC, Kenny2github commented on resources/main.js
> +        tempItem.style.left = "0";
Why have any chance of showing it? -999 and -999 should be fine.

2020-10-10 19:48 UTC, Kenny2github requested changes

2020-10-10 19:48 UTC, Kenny2github commented on resources/main.js
> +        alert(mw.message( 'scratch-confirmaccount-click-copy-alert').plain());
Please use a [bubble notification](https://www.mediawiki.org/wiki/Bubble_notifications) for this.

2020-10-10 19:48 UTC, Kenny2github commented on resources/main.js
> +        tempItem.style.left = "0";
Why have any chance of showing it?
```suggestion
        tempItem.style.top = "-999px";
        tempItem.style.left = "-999px";
```

2020-10-10 19:48 UTC, Kenny2github commented on src/SpecialRequestAccount.php
> +		   'id' => 'mw-scratch-confirmaccount-verifcode'
Weird indentation here

2020-10-10 20:32 UTC, Kenny2github requested changes
See also the conversation I unresolved

2020-10-10 20:32 UTC, Kenny2github commented on extension.json
> +			]
Weird indentation here

2020-10-11 08:40 UTC, SausageMcSauce commented
This might not be considered a problem (and I am not going against anyone), but this pull request contains 57 commits from the requestor, and this getting merged might litter the commit history of this repository with all of those commits, some of which contain very minor changes.

2020-10-11 10:23 UTC, Kenny2github commented
@SausageMcSauce Squash merging is a thing. All commits from this branch will be combined into one commit when merging.

2020-10-11 10:34 UTC, Kenny2github approved these changes

2020-10-11 10:34 UTC, merged